// <auto-generated />
using System;
using FullPost.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullPost.Migrations
{
    [DbContext(typeof(FullPostContext))]
    [Migration("20251116122031_FullPost")]
    partial class FullPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FullPost.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FacebookAccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FacebookPageId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FacebookPageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FacebookTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FacebookUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleAccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleRefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GoogleTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstagramAccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("InstagramTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstagramUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstagramUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkedInAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("LinkedInProfileUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LinkedInTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkedInUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("LinkedInUsername")
                        .HasColumnType("longtext");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TikTokAccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TikTokRefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TikTokTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TikTokUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TikTokUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TwitterAccessSecret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TwitterAccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TwitterTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TwitterUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TwitterUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("YouTubeAccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeChannelId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeChannelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeProfilePicture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeRefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("YouTubeTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FullPost.Entities.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoSubscribe")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FullPost.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FacebookPostId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FacebookPostLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstagramPostId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstagramPostLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkedInPostId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkedInPostLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MediaUrls")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TikTokPostId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TikTokPostLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TwitterPostId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TwitterPostLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("YouTubePostId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubePostLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("FullPost.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoOfPosts")
                        .HasColumnType("longtext");

                    b.Property<string>("PaystackPlanCode")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("FullPost.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NoOfPostsThisMonth")
                        .HasColumnType("int");

                    b.Property<string>("PaystackCustomerCode")
                        .HasColumnType("longtext");

                    b.Property<string>("PaystackSubscriptionCode")
                        .HasColumnType("longtext");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("FullPost.Entities.Customer", b =>
                {
                    b.HasOne("FullPost.Entities.Identity.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("FullPost.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FullPost.Entities.UserSubscription", b =>
                {
                    b.HasOne("FullPost.Entities.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FullPost.Entities.Identity.User", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
